version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/traefik"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"

  - package-ecosystem: "docker"
    directory: "/shared-services"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"

  - package-ecosystem: "docker"
    directory: "/nextcloud"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"

  - package-ecosystem: "docker"
    directory: "/uptime-kuma"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"

  - package-ecosystem: "docker"
    directory: "/zammad"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
